name: GitHub Metrics

on:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_color: blue

      - name: Generate Languages Activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
